export enum Country {
    Canada = "canada",
    America = "america"
}

export const canadaCodes = [
    {code: "YT", display: "Yukon"},
    {code: "NT", display: "Northwest Territories"},
    {code: "NU", display: "Nunavut"},
    {code: "BC", display: "British Columbia"},
    {code: "AB", display: "Alberta"},
    {code: "SK", display: "Saskatchewan"},
    {code: "MB", display: "Manitoba"},
    {code: "ON", display: "Ontario"},
    {code: "QC", display: "Quebec"},
    {code: "NL", display: "Newfoundland & Labrador"},
    {code: "NS", display: "Nova Scotia"},
    {code: "PE", display: "Prince Edward Island"},
    {code: "NB", display: "New Brunswick"}
]

export const americaCodes = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AR": "Arkansas",
    "AZ": "Arizona",
    "CA": "California",
    "CT": "Connecticut",
    "CO": "Colorado",
    "DC": "District of Columbia",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "GU": "Guam",
    "HI": "Hawaii",
    "IA": "Iowa",
    "ID": "Idaho",
    "IN": "Indiana",
    "IL": "Illinois",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "MA": "Massachusetts",
    "MD": "Maryland",
    "ME": "Maine",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MO": "Missouri",
    "MS": "Mississippi",
    "MT": "Montana",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "NE": "Nebraska",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NV": "Nevada",
    "NY": "New York",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "PR": "Puerto Rico",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VA": "Virginia",
    "VI": "Virgin Islands",
    "VT": "Vermont",
    "WA": "Washington",
    "WI": "Wisconsin",
    "WV": "West Virginia",
    "WY": "Wyoming",

    /*
    "RP": "RP",
    "US": "US",
    "MH": "MH",
    "FM": "FM",
    "IH2": "IH2",
    "LTC": "LTC",
    "VA2": "VA2",
    "DD2": "DD2",
    "BP2": "BP2",
    */
}
