export enum Country {
    Canada = "canada",
    America = "america"
}

// Fallback values provided for 4 regions as their Display values do not match their key in the returned
// data from the OpenCOVID API
export const canadaCodes = [
    {code: "YT", display: "Yukon"},
    {code: "NT", display: "Northwest Territories", dataset: "NWT"},
    {code: "NU", display: "Nunavut"},
    {code: "BC", display: "British Columbia", dataset: "BC"},
    {code: "AB", display: "Alberta"},
    {code: "SK", display: "Saskatchewan"},
    {code: "MB", display: "Manitoba"},
    {code: "ON", display: "Ontario"},
    {code: "QC", display: "Quebec"},
    {code: "NL", display: "Newfoundland & Labrador", dataset: "NL"},
    {code: "NS", display: "Nova Scotia"},
    {code: "PE", display: "Prince Edward Island", dataset: "PEI"},
    {code: "NB", display: "New Brunswick"}
]

export const americaCodes = [
    {code: "AL", display: "Alabama"},
    {code: "AK", display: "Alaska"},
    {code: "AR", display: "Arkansas"},
    {code: "AZ", display: "Arizona"},
    {code: "CA", display: "California"},
    {code: "CT", display: "Connecticut"},
    {code: "CO", display: "Colorado"},
    {code: "DC", display: "District of Columbia"},
    {code: "DE", display: "Delaware"},
    {code: "FL", display: "Florida"},
    {code: "GA", display: "Georgia"},
    {code: "GU", display: "Guam"},
    {code: "HI", display: "Hawaii"},
    {code: "IA", display: "Iowa"},
    {code: "ID", display: "Idaho"},
    {code: "IN", display: "Indiana"},
    {code: "IL", display: "Illinois"},
    {code: "KS", display: "Kansas"},
    {code: "KY", display: "Kentucky"},
    {code: "LA", display: "Louisiana"},
    {code: "MA", display: "Massachusetts"},
    {code: "MD", display: "Maryland"},
    {code: "ME", display: "Maine"},
    {code: "MI", display: "Michigan"},
    {code: "MN", display: "Minnesota"},
    {code: "MO", display: "Missouri"},
    {code: "MS", display: "Mississippi"},
    {code: "MT", display: "Montana"},
    {code: "NC", display: "North Carolina"},
    {code: "ND", display: "North Dakota"},
    {code: "NE", display: "Nebraska"},
    {code: "NH", display: "New Hampshire"},
    {code: "NJ", display: "New Jersey"},
    {code: "NM", display: "New Mexico"},
    {code: "NV", display: "Nevada"},
    {code: "NY", display: "New York"},
    {code: "OH", display: "Ohio"},
    {code: "OK", display: "Oklahoma"},
    {code: "OR", display: "Oregon"},
    {code: "PA", display: "Pennsylvania"},
    {code: "PR", display: "Puerto Rico"},
    {code: "RI", display: "Rhode Island"},
    {code: "SC", display: "South Carolina"},
    {code: "SD", display: "South Dakota"},
    {code: "TN", display: "Tennessee"},
    {code: "TX", display: "Texas"},
    {code: "UT", display: "Utah"},
    {code: "VA", display: "Virginia"},
    {code: "VI", display: "Virgin Islands"},
    {code: "VT", display: "Vermont"},
    {code: "WA", display: "Washington"},
    {code: "WI", display: "Wisconsin"},
    {code: "WV", display: "West Virginia"},
    {code: "WY", display: "Wyoming"}
]
